helium/denylist

.github/workflows/ci.yml

The checked in files are available via the source code tarballs

Remove unneeded files from release

---

README.md

Ultimately this repo will move to a Nova Labs GitHub team.

Clarify Ownership

---

manifest.json
public_key.json

See https://docs.helium.com/devblog/2023/08/07/denylist-evolution/ and the recent recordings/minutes of the IoT working group.
Note that this initial denylist is very conservative. We plan to publish a new denylist weekly and continue to refine our methodology to detect more methods of cheating.

Add first algorithmic denylist

---

manifest.json
public_key.json

Revert "Add first algorithmic denylist"

---

manifest.json

Same parameters are previous list. Data is september 25th through october 8th.

New algorithmic denylist for October 8th

---

manifest.json

needs report prefix and uploads.

denylist 2023110601

---

manifest.json

No changes to parameters or classifiers for this list.

New denylist for october 30 to november 13

---

manifest.json

No parameter changes in this denylist.

New denylist for November 13 to November 27th

---

manifest.json

No denylist parameters have changed

New denylist for Nov 27 to Dec 11

---

manifest.json

Summary
----
- Algorithmic denylist for Feb 12, 2024 - Feb 26, 2024.
- No changes to the algorithm from the previous denylist.

Denylist for Feb 12 - Feb 26

---

manifest.json

Summary
----
- Algorithmic denylist for Feb 19, 2024 - Mar 04, 2024
- No changes from the previous algorithm.
TODO:

Algorithmic Denylist for Feb 19 - Mar 04

---

manifest.json

No classifier changes over last week

Denylist for march 04 to march 18

---

manifest.json

Denylist statistics:
carryover (nodes): 1501
carryover (edges): 2818122
antenna split/too close: 15869
disjoint reciprocity: 42
Edge classifiers
terrain intersection: 2700225
distance insensitivity: 2083624
ingest latency: 15189

Denylist for april 01 to april 15th, no classifier changes

---

manifest.json

Statistics
----
carryover (nodes): 2399
carryover (edges): 2910187
antenna split/too close: 12556
disjoint reciprocity: 37
Edge classifiers
terrain intersection: 2816449
distance insensitivity: 2074556
ingest latency: 9674

Denylist for Apr 29 to May 13, no classifier changes

---

manifest.json

Stats
----
carryover (nodes): 2573
carryover (edges): 3040823
antenna split/too close: 11890
disjoint reciprocity: 48
Edge classifiers
terrain intersection: 2703637
distance insensitivity: 2003751
ingest latency: 7631
TODO:

Denylist for May06 to May20, no classifier changes

---

manifest.json

Stats
----
carryover (nodes): 2672
carryover (edges): 3084019
antenna split/too close: 11519
disjoint reciprocity: 49
terrain intersection: 2731470
distance insensitivity: 2007125
ingest latency: 8796

Denylist for May13 to May27, no classifier changes

---

manifest.json

Stats
----
carryover (nodes): 2874
carryover (edges): 3076091
antenna split/too close: 11144
disjoint reciprocity: 45
terrain intersection: 2811716
distance insensitivity: 2179547
ingest latency: 7859

Denylist for May20 to Jun03, no classifier changes

---

manifest.json

Stats
----
carryover (nodes): 2794
carryover (edges): 3296344
antenna split/too close: 11003
disjoint reciprocity: 39
terrain intersection: 2680281
distance insensitivity: 211120
ingest latency: 6604

Denylist for May27 to Jun10, no classifier changes

---

manifest.json

carryover (nodes): 2902
carryover (edges): 3388976
antenna split/too close: 10584
disjoint reciprocity: 42
terrain intersection: 2587066
distance insensitivity: 2083985
ingest latency: 4372

Denylist for June 03 to June 17, no classifier Changes

---

manifest.json

Stats
----
carryover (nodes): 3192
carryover (edges): 3484409
antenna split/too close: 10038
disjoint reciprocity: 44
terrain intersection: 2584269
distance insensitivity: 1955805
ingest latency: 2542

Denylist for June 10 to June 24, no classifier Changes

---

manifest.json

Stats:
carryover (nodes): 3353
carryover (edges): 3576510
antenna split/too close: 9363
disjoint reciprocity: 46
terrain intersection: 2671703
distance insensitivity: 1796323
ingest latency: 3885

Denylist for June 24 to July 8, no classifier changes

---

manifest.json

Stats:
carryover (nodes): 3376
carryover (edges): 3790831
antenna split/too close: 9299
disjoint reciprocity: 51
terrain intersection: 2438526
distance insensitivity: 1865438
ingest latency: 3706

Denylist for July 1 to July 15, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): 3412
carryover (edges): 3688071
antenna split/too close: 8964
disjoint reciprocity: 52
terrain intersection: 2854559
distance insensitivity: 1941006
ingest latency: 4160

Denylist for July 15 to July 29, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): 3474
carryover (edges): 3969516
antenna split/too close: 8680
disjoint reciprocity: 43
terrain intersection: 2542407
distance insensitivity: 1889967
ingest latency: 3872

Denylist for July 22 to Aug 05, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): 3518
carryover (edges): 3928632
antenna split/too close: 8520
disjoint reciprocity: 47
terrain intersection: 2616527
distance insensitivity: 1914770
ingest latency: 3419

Denylist for July 29 to Aug 12, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **3533**
carryover (edges): **4019733**
antenna split/too close: **8418**
disjoint reciprocity: **41**
terrain intersection: **2566306**
distance insensitivity: **1943353**
ingest latency: **3352**
TODO:

Denylist for Aug 05 to Aug 19, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **3533**
carryover (edges): **4019733**
antenna split/too close: **8418**
disjoint reciprocity: **41**
terrain intersection: **2566306**
distance insensitivity: **1943353**
ingest latency: **3352**

Denylist for Aug 12 to Aug 26, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **3672**
carryover (edges): **4059311**
antenna split/too close: **8111**
disjoint reciprocity: **55**
terrain intersection: **2701422**
distance insensitivity: **1925260**
ingest latency: **3548**
TODO:

Denylist for Aug 19 to Sep 02, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **3642**
carryover (edges): **4133974**
antenna split/too close: **8051**
disjoint reciprocity: **56**
terrain intersection: **2647132**
distance insensitivity: **1907071**
ingest latency: **2896**

Denylist for Aug 26 to Sep 09, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **3609**
carryover (edges): **4366887**
antenna split/too close: **7875**
disjoint reciprocity: **54**
terrain intersection: **2441369**
distance insensitivity: **1870522**
ingest latency: **3921**

Denylist for Sep 02 to Sep 16, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **3513**
carryover (edges): **4325404**
antenna split/too close: **7853**
disjoint reciprocity: **54**
terrain intersection: **2530229**
distance insensitivity: **1991281**
ingest latency: **4083**
TODO:

Denylist for Sep 09 to Sep 23, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **3423**
carryover (edges): **4408405**
antenna split/too close: **7723**
disjoint reciprocity: **71**
terrain intersection: **2441004**
distance insensitivity: **2015149**
ingest latency: **3302**
TODO:

Denylist for Sep 16 to Sep 30, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **2960**
carryover (edges): **4571214**
antenna split/too close: **7578**
disjoint reciprocity: **55**
terrain intersection: **2249275**
distance insensitivity: **1952142**
ingest latency: **4064**
TODO:

Denylist for Sep 23 to Oct 07, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **2750**
carryover (edges): **4703199**
antenna split/too close: **7544**
disjoint reciprocity: **53**
terrain intersection: **2094221**
distance insensitivity: **2003182**
ingest latency: **3253**
TODO:

Denylist for Sep 30 to Oct 14, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **2583**
carryover (edges): **4808671**
antenna split/too close: **7544**
disjoint reciprocity: **46**
terrain intersection: **2026133**
distance insensitivity: **1851324**
ingest latency: **3193**

Denylist for Oct 07 to Oct 21, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **2504**
carryover (edges): **4929262**
antenna split/too close: **7506**
disjoint reciprocity: **54**
terrain intersection: **1975060**
distance insensitivity: **1723076**
ingest latency: **2530**

Denylist for Oct 14 to Oct 28, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **2415**
carryover (edges): **4979303**
antenna split/too close: **7346**
disjoint reciprocity: **96**
terrain intersection: **1882922**
distance insensitivity: **1641227**
ingest latency: **1981**

Denylist for Oct 21 to Nov 04, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **2329**
carryover (edges): **5013206**
antenna split/too close: **7271**
disjoint reciprocity: **77**
terrain intersection: **1829987**
distance insensitivity: **1565357**
ingest latency: **2052**

Denylist for Oct 28 to Nov 11, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **2277**
carryover (edges): **4940654**
antenna split/too close: **7177**
disjoint reciprocity: **94**
terrain intersection: **1903823**
distance insensitivity: **1707406**
ingest latency: **1021**
TODO:

Denylist for Nov 04 to Nov 18, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **2115**
carryover (edges): **4946540**
antenna split/too close: **7133**
disjoint reciprocity: **96**
terrain intersection: **1912399**
distance insensitivity: **1837122**
ingest latency: **1973**

Denylist for Nov 18 to Dec 02, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **2042**
carryover (edges): **5188752**
antenna split/too close: **7081**
disjoint reciprocity: **90**
terrain intersection: **1641071**
distance insensitivity: **1648459**
ingest latency: **2957**

Denylist for Nov 25 to Dec 09, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1850**
carryover (edges): **5155221**
antenna split/too close: **7097**
disjoint reciprocity: **86**
terrain intersection: **1677903**
distance insensitivity: **1733337**
ingest latency: **3764**

Denylist for Dec 02 to Dec 16, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1745**
carryover (edges): **5003789**
antenna split/too close: **6900**
disjoint reciprocity: **102**
terrain intersection: **1947626**
distance insensitivity: **1733573**
ingest latency: **4895**
TODO:

Denylist for Dec 16 to Dec 30, no classifier changes

---

manifest.json

Summary
carryover (nodes): **1768**
carryover (edges): **5072764**
community inclusions: 98950
antenna split/too close: **6757**
disjoint reciprocity: **78**
terrain intersection: **1902503**
distance insensitivity: **1594902**
ingest latency: **3884**
TODO:

Denylist for Dec 23 to Jan 06, no classifier changes

---

manifest.json

Summary
carryover (nodes): **1788**
carryover (edges): **5606530**
antenna split/too close: **6636**
disjoint reciprocity: **66**
terrain intersection: **1357128**
distance insensitivity: **1303143**
ingest latency: **3446**
TODO:

Denylist for Dec 30 to Jan 13, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1869**
carryover (edges): **5788850**
antenna split/too close: **6468**
disjoint reciprocity: **62**
terrain intersection: **1255285**
distance insensitivity: **1171921**
ingest latency: **433**

Denylist for Jan 20  to Feb 03, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1831**
carryover (edges): **5846308**
antenna split/too close: **6295**
disjoint reciprocity: **65**
terrain intersection: **1201703**
distance insensitivity: **1198581**
ingest latency: **788**
TODO:

Denylist for Jan 27 to Feb 10, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1813**
carryover (edges): **5985416**
antenna split/too close: **6312**
disjoint reciprocity: **66**
terrain intersection: **1024585**
distance insensitivity: **1153303**
ingest latency: **1321**

Denylist for Feb 03 to Feb 17, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1742**
carryover (edges): **5997350**
antenna split/too close: **6260**
disjoint reciprocity: **69**
terrain intersection: **1013671**
distance insensitivity: **1148863**
ingest latency: **825**

Denylist for Feb 10 to Feb 24, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1728**
carryover (edges): **5904277**
antenna split/too close: **6083**
disjoint reciprocity: **68**
terrain intersection: **1129334**
distance insensitivity: **11090988**
ingest latency: **517**

Denylist for Feb 17 to Mar 03, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1684**
carryover (edges): **5734204**
antenna split/too close: **5993**
disjoint reciprocity: **71**
terrain intersection: **1450691**
distance insensitivity: **1167110**
ingest latency: **149**

Denylist for Feb 24 to Mar 10, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1618**
carryover (edges): **5817196**
antenna split/too close: **5852**
disjoint reciprocity: **66**
terrain intersection: **1340707**
distance insensitivity: **1180116**
ingest latency: **901**

Denylist for Mar 10 to Mar 24, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1600**
carryover (edges): **5948054**
antenna split/too close: **5720**
disjoint reciprocity: **68**
terrain intersection: **1179888**
distance insensitivity: **1126303**
ingest latency: **551**

Denylist for Mar 17 to Mar 31, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1581**
carryover (edges): **6004671**
antenna split/too close: **5561**
disjoint reciprocity: **65**
terrain intersection: **1152748**
distance insensitivity: **1056288**
ingest latency: **451**

Denylist for March 31 to April 14, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1594**
carryover (edges): **5942159**
antenna split/too close: **5514**
disjoint reciprocity: **81**
terrain intersection: **1216218**
distance insensitivity: **1096726**
ingest latency: **680**

Denylist for April 7 to April 21, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1587**
carryover (edges): **5944466**
antenna split/too close: **5415**
disjoint reciprocity: **74**
terrain intersection: **1237082**
distance insensitivity: **1145993**
ingest latency: **1261**

Denylist for Apr 14 to Apr 28, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1544**
carryover (edges): **5859209**
antenna split/too close: **5222**
disjoint reciprocity: **74**
terrain intersection: **1459550**
distance insensitivity: **1107672**
ingest latency: **1030**

Denylist for Apr 28 to May 12, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1492**
carryover (edges): **6126106**
antenna split/too close: **5171**
disjoint reciprocity: **73**
terrain intersection: **1132867**
distance insensitivity: **1052615**
ingest latency: **952**

Denylist for May 05 to May 19, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1449**
carryover (edges): **6018735**
antenna split/too close: **5110**
disjoint reciprocity: **72**
terrain intersection: **1380355**
distance insensitivity: **1052490**
ingest latency: **665**

Denylist for May 19 to Jun 02, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1399**
carryover (edges): **6169596**
antenna split/too close: **4883**
disjoint reciprocity: **74**
terrain intersection: **1304102**
distance insensitivity: **911618**
ingest latency: **1470**

Denylist for Jun 09 to Jun 23, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1393**
carryover (edges): **6161834**
antenna split/too close: **4704**
disjoint reciprocity: **77**
terrain intersection: **1340042**
distance insensitivity: **934374**
ingest latency: **788**

Denylist for Jun 16 to Jun 30, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1336**
carryover (edges): **6078282**
antenna split/too close: **4695**
disjoint reciprocity: **65**
terrain intersection: **1539751**
distance insensitivity: **938144**
ingest latency: **399**

Denylist for Jun 23 to Jul 07, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1119**
carryover (edges): **6389947**
antenna split/too close: **4557**
disjoint reciprocity: **56**
terrain intersection: **1159549**
distance insensitivity: **933579**
ingest latency: **128**

Denylist for Jul 07 to Jul 21, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1162**
carryover (edges): **6414473**
antenna split/too close: **4483**
disjoint reciprocity: **70**
terrain intersection: **1168313**
distance insensitivity: **983841**
ingest latency: **169**

Denylist for Jul 21 to Aug 04, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1178**
carryover (edges): **6413302**
antenna split/too close: **4342**
disjoint reciprocity: **68**
terrain intersection: **1197307**
distance insensitivity: **956215**
ingest latency: **38**

Denylist for Jul 28 to Aug 11, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1119**
carryover (edges): **6547552**
community inclusions: **104378**
antenna split/too close: **4204**
disjoint reciprocity: **76**
terrain intersection: **1113640**
distance insensitivity: **950616**
ingest latency: **46**

Denylist for Aug 18 to Sep 01, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1121**
carryover (edges): **6623084**
community inclusions: **104378**
antenna split/too close: **4140**
disjoint reciprocity: **67**
terrain intersection: **1084039**
distance insensitivity: **833180**
ingest latency: **315**

Denylist for Aug 25 to Sep 08, no classifier changes

---

manifest.json

Summary
----
carryover (nodes): **1072**
carryover (edges): **6825717**
community inclusions: **104477**
antenna split/too close: **4022**
disjoint reciprocity: **71**
terrain intersection: **800050**
distance insensitivity: **818648**
ingest latency: **42**

Denylist for Sep 22 to Oct 06, no classifier changes
